### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by lucasxulo18** [rootxnova/tiktok_views#1]
not work for me bro

**Comment by lucasxulo18** [comment]
Traceback (most recent call last):
  File "E:\ARCHIVOS\BOT CHROME v60 v2\Data\tiktok view.py", line 32, in <module>
    accp = driver.find_element_by_xpath('//*[@id="closeAnnouncementsModal"]').click()
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="closeAnnouncementsModal"]"}
